import SEO from "../../components/common/SEO.jsx";

const Terms = () => {
  return (
    <>
      <SEO
        title="Terms & Conditions"
        description="Read the Terms & Conditions for using Ask Me Something, including rules for using our AI-powered question answering services."
        keywords="Ask Me Something terms and conditions, AI terms of service, terms of use"
      />

      <section className="mx-auto max-w-4xl px-4 py-20 sm:px-6">
        <div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm sm:p-12">
          <h1 className="text-4xl font-bold text-slate-900">
            Terms & Conditions
          </h1>

          <p className="mt-4 text-sm text-slate-500">
            Last updated: September 13, 2026
          </p>

          <p className="mt-6 leading-7 text-slate-600">
            Welcome to Ask Me Something. By accessing or using our website and
            services, you agree to these Terms & Conditions. If you do not agree
            with these terms, please do not use the service.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            Use of Our Service
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            Ask Me Something provides an AI-powered platform that allows users
            to submit questions through text, images, and voice and receive
            AI-generated responses.
          </p>

          <p className="mt-4 leading-7 text-slate-600">
            You agree to use the service only for lawful purposes and in a way
            that does not interfere with the operation or security of the
            website.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            User Accounts
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            Some features require you to create an account. You are responsible
            for providing accurate information and keeping your account
            credentials secure.
          </p>

          <p className="mt-4 leading-7 text-slate-600">
            You are responsible for activity performed through your account.
            Please contact us if you believe your account has been accessed
            without authorization.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            AI-Generated Answers
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            Responses generated by our AI systems are provided for general
            informational and educational purposes. AI-generated information may
            contain errors, omissions, or outdated information.
          </p>

          <p className="mt-4 leading-7 text-slate-600">
            You should independently verify important information before relying
            on it, particularly for medical, legal, financial, educational,
            safety, or other high-impact decisions.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            User Content
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            You are responsible for the questions, images, voice recordings, and
            other content you submit to Ask Me Something.
          </p>

          <p className="mt-4 leading-7 text-slate-600">
            You agree not to submit content that is illegal, harmful,
            fraudulent, abusive, or that violates the rights of another person.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            Prohibited Activities
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            You must not attempt to misuse, disrupt, reverse engineer, overload,
            or gain unauthorized access to our website, APIs, servers, accounts,
            or other systems.
          </p>

          <p className="mt-4 leading-7 text-slate-600">
            Automated abuse, attempts to bypass usage restrictions, and
            activities intended to interfere with the service are prohibited.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            Intellectual Property
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            The website, branding, design, software, logos, and other original
            materials provided by Ask Me Something are protected by applicable
            intellectual property laws.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            Third-Party Services
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            Our service may depend on third-party services for AI processing,
            hosting, analytics, authentication, security, and advertising.
            Availability and functionality of those services may change without
            notice.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            Availability of the Service
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            We aim to keep Ask Me Something available and reliable, but we do
            not guarantee that the service will always be available,
            uninterrupted, or error-free.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            Disclaimer
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            Ask Me Something is provided on an "as available" basis. We do not
            guarantee the accuracy, completeness, reliability, or suitability of
            every AI-generated response.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            Changes to These Terms
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            We may update these Terms & Conditions when necessary. Updated terms
            will be posted on this page along with a revised "Last updated"
            date.
          </p>

          <h2 className="mt-10 text-2xl font-bold text-slate-900">
            Contact Us
          </h2>

          <p className="mt-4 leading-7 text-slate-600">
            If you have questions about these Terms & Conditions, contact us at:
          </p>

          <a
            href="mailto:support@askmesomething.site"
            className="mt-4 inline-block font-semibold text-blue-600 hover:text-blue-700"
          >
            support@askmesomething.site
          </a>
        </div>
      </section>
    </>
  );
};

export default Terms;
